const messages = [
    "Believe you can and you're halfway there.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "You are never too old to set another goal or to dream a new dream.",
    "Act as if what you do makes a difference. It does.",
    "Success usually comes to those who are too busy to be looking for it.",
    "Don't watch the clock; do what it does. Keep going.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "It always seems impossible until it's done.",
    "You don't have to be great to start, but you have to start to be great.",
    "Everything you've ever wanted is on the other side of fear.",
    "Opportunities don't happen, you create them.",
    "Dream big and dare to fail.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "If you can dream it, you can do it.",
    "Do what you can, with what you have, where you are.",
    "The secret of getting ahead is getting started.",
    "Quality is not an act, it is a habit.",
    "Life is 10% what happens to you and 90% how you react to it.",
    "If you're going through hell, keep going.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your time is limited, don't waste it living someone else's life.",
    "Winning isn't everything, but wanting to win is.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "Every child is an artist. The problem is how to remain an artist once he grows up.",
    "You can never cross the ocean until you have the courage to lose sight of the shore.",
    "I've missed more than 9000 shots in my career. I've failed over and over and over again in my life. And that is why I succeed.",
    "The two most important days in your life are the day you are born and the day you find out why.",
    "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.",
    "The only person you are destined to become is the person you decide to be.",
    "Go confidently in the direction of your dreams. Live the life you have imagined.",
    "When I let go of what I am, I become what I might be.",
    "Everything has beauty, but not everyone can see.",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    "When one door of happiness closes, another opens.",
    "Do one thing every day that scares you.",
    "Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers.",
    "Do what you feel in your heart to be right - for you'll be criticized anyway.",
    "Happiness is not something ready made. It comes from your own actions.",
    "Whatever you are, be a good one.",
    "The same boiling water that softens the potato hardens the egg. It's what you're made of. Not the circumstances.",
    "If we have the attitude that it's going to be a great day it usually is.",
    "You can either experience the pain of discipline or the pain of regret. The choice is yours.",
    "Impossible is just an opinion.",
    "Your passion is waiting for your courage to catch up.",
    "Magic is believing in yourself. If you can make that happen, you can make anything happen.",
    "If something is important enough, even if the odds are against you, you should still do it.",
    "Hold the vision, trust the process.",
    "Don't be afraid to give up the good to go for the great.",
    "One day or day one. You decide.",
    "Invest in your dreams. Grind now. Shine later.",
    "The hard days are what make you stronger.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "Work hard in silence, let your success be your noise.",
    "Discipline is doing what needs to be done, even if you don't want to do it.",
    "Hard work beats talent when talent doesn't work hard.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Character is power.",
    "To live a creative life, we must lose our fear of being wrong.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Trust because you are willing to accept the risk, not because it's safe or certain.",
    "Take up one idea. Make that one idea your life--think of it, dream of it, live on it.",
    "All our dreams can come true if we have the courage to pursue them.",
    "Good things come to people who wait, but better things come to those who go out and get them.",
    "If you do what you always did, you will get what you always got.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Just when the caterpillar thought the world was ending, he turned into a butterfly.",
    "Successful people do what unsuccessful people are not willing to do.",
    "The dream is free. The hustle is sold separately.",
    "Don't stop when you're tired. Stop when you're done.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It's going to be hard, but hard does not mean impossible.",
    "Don't wait for opportunity. Create it.",
    "Sometimes later becomes never. Do it now.",
    "Great things never came from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop until you're proud.",
    "We generate fears while we sit. We overcome them by action.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Be so good they can't ignore you.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "You are enough just as you are.",
    "Focus on the step in front of you, not the whole staircase.",
    "Positive anything is better than negative nothing.",
    "Preparation is the key to success.",
    "Failure is the condiment that gives success its flavor.",
    "Wake up with determination. Go to bed with satisfaction.",
    "It's a slow process, but quitting won't speed it up.",
    "You didn't come this far to only come this far.",
    "Be the change that you wish to see in the world.",
    "In the middle of every difficulty lies opportunity.",
    "Start where you are. Use what you have. Do what you can.",
    "Fall seven times and stand up eight.",
    "Simplicity is the ultimate sophistication."
]